spring.application.name=Biblioteca

spring.datasource.url=jdbc:oracle:thin:@//192.168.0.200:1522/UNIFIL
spring.datasource.username=unifil
spring.datasource.password=unifil
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=create
jwt.secret="OzRQpJvK5n7FPIVH0ul4Na6jIZlZnkbENzNIvnJ35jX"